export interface AcenteDetail{
    acenteId:number;
    acenteAdi:string;
    eMail:string;
    sifre:string;
    adres:string;
    firmaUnvan:string;
    yetkili:string;
    telefon:string;
    sehirId:number;
    ulkeId:number;
    sozlesme:number;
    sozlesmeOnayTarih:Date;
    notlar:string;
    faturaAdres:string;
    ıban:string;
    vergiDaire:string;
    vergiDaireNo:string;
    yetkiliTel:string;
    yetkiliEmail:string;
    kredi:number;
    kayitTarih:Date;
    ulkeAdi:string;
    sehirAd:string;
}