export interface TransferDetail{
    transferId:number;
    ulkeId:number;
    sehirId:number;
    aracId:number;
    dilId:number;
    sehirAd:string;
    ulkeAdi:string;
    aracAdi:string;
    nereden:string;
    nereye:string;
    kisiSayisi:number;
    bagajSayisi:number;
    tarih:Date;
    saat:Date;
    km:number;
    sureSaat:string;
    fiyat:number;
    ekstrasizFiyat:number;
    uyeId:number;
    doviz:number;
    uyeAd:string;
    uyeSoyad:string;
    eMail:string;
    telefon:string;
}